lightning_model:
  model:
    target: modules.torch_modules.SSLHead
    params:
      spatial_dims: 3
      in_channels: 1
      feature_size: 48
      depths:
        - 2
        - 2
        - 2
        - 2
      dropout_path_rate: 0.0
      use_checkpoint: True
  loss:
    target: modules.losses.Loss
    params:
      batch_size: 4
      device: "cuda"
  optimizer:
    target: torch.optim.Adam
  scheduler:
    target: torch.optim.lr_scheduler.CosineAnnealingLR
  params:
    initial_lr: 1e-4

trainer:
  callbacks:
    target:
      early_stopping: pytorch_lightning.callbacks.EarlyStopping
      model_checkpoint: pytorch_lightning.callbacks.ModelCheckpoint
      lr_monitor: pytorch_lightning.callbacks.LearningRateMonitor
    params:
      early_stopping:
        monitor: "val_total_loss"
        min_delta: 1e-4
        patience: 40
        verbose: True
        mode: "min"
      model_checkpoint:
        dirpath: "pt_models/"
        filename: "best_SSLModel_resampled_new"
        monitor: "val_total_loss"
        mode: "min"
        save_top_k: 1
      lr_monitor:
        logging_interval: "step"
  params:
    max_epochs: 200
    accelerator: "gpu"
    check_val_every_n_epoch: 1
    log_every_n_steps: 1
    precision: "16-mixed"

train_dataset:
  params:
    images_dir: "/mnt/c/Users/Carlini/Desktop/Gianluca/QSM_GV_GC/splits_resampled/train"
    patch_size: -1
    threshold: 0.0

train_dataloader:
  params:
    batch_size: 4
    shuffle: True
    num_workers: 24

val_dataset:
  params:
    images_dir: "/mnt/c/Users/Carlini/Desktop/Gianluca/QSM_GV_GC/splits_resampled/test"
    patch_size: -1
    threshold: 0.0

val_dataloader:
  params:
    batch_size: 4
    shuffle: True
    num_workers: 24